### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by NarelyLima** [joaoipiraja/fastmenu#3]
https://github.com/joaoipiraja/fastmenu/blob/28f99ba2170d8db0129404153a602635c051df2f/Sources/fastmenu/main.swift#L9

Qual a diferença desse função para as demais?

https://github.com/joaoipiraja/fastmenu/blob/28f99ba2170d8db0129404153a602635c051df2f/Sources/fastmenu/food.swift#L54

Qual a utilização do .nan?

https://github.com/joaoipiraja/fastmenu/blob/28f99ba2170d8db0129404153a602635c051df2f/Sources/fastmenu/main.swift#L49-L55

Me explica ou manda um documento explicando @Flag() e @Option

Seu trabalho está muito bem feito, você usou algo que eu não pensaria duas vezes em sair correndo. Parabéns, espero adquirir mais contato com você para poder aprender mais e mais.

**Comment by joaoipiraja** [comment]
A priori, fico feliz que tenha gostado! 😁

A `@Flag` funciona como um booleano  e o `@Option` um argumento opcional  dentro do [Argument Passer](https://github.com/apple/swift-argument-parser)
